name: Multi Platform Building Jobs

on:
  push:
    branches:
      - master

jobs:
  macOS:
    name: MacOS Platform Build
    runs-on: macOS-latest
    steps:
      - name: Check source code
        uses: actions/checkout@master
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Build environment
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Assemble artifact
        shell: bash
        run: |
          pyinstaller -F --icon=./resources/app.icns --noconsole MagicDrCOM.py
          rm -rf ./artifact/ && mkdir -p ./artifact/ && mv ./dist/MagicDrCOM.app ./artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: macOS platform application
          path: ./artifact/

  Linux:
    name: Linux Platform Build
    runs-on: ubuntu-latest
    steps:
      - name: Check source code
        uses: actions/checkout@master
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Build environment
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Assemble artifact
        shell: bash
        run: |
          pyinstaller -F --icon=./resources/app.ico --noconsole MagicDrCOM.py
          rm -rf ./artifact/ && mkdir -p ./artifact/ && mv ./dist/MagicDrCOM.app ./artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: linux platform application
          path: ./artifact/

  Windows:
    name: Windows Platform Build
    runs-on: windows-latest
    steps:
      - name: Check source code
        uses: actions/checkout@master
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Build environment
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Assemble artifact
        shell: bash
        run: |
          pyinstaller -F --icon=./resources/app.ico --noconsole MagicDrCOM.py
          rm -rf ./artifact/ && mkdir -p ./artifact/ && mv ./dist/MagicDrCOM.app ./artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: linux platform application
          path: ./artifact/

